CREATE TABLE INFORMATIONS
       (ID NUMBER CONSTRAINT PK_INFO_ID PRIMARY KEY, 
        NAME VARCHAR2(50), 
        ADDRESS VARCHAR2(50),
        PHONE VARCHAR2(15),
        USERTYPE VARCHAR2(20));

CREATE TABLE USERS
       (ID NUMBER CONSTRAINT PK_USER_ID PRIMARY KEY, 
        UNAME VARCHAR2(50), 
        PWORD VARCHAR2(50),
        PERMISSION NUMBER(4),
        INFO_ID NUMBER(4) CONSTRAINT FK_INFO_ID REFERENCES INFORMATIONS,
        USERTYPE VARCHAR2(20));
        
CREATE TABLE CATEGORIES
       (ID NUMBER CONSTRAINT PK_CAT_ID PRIMARY KEY, 
        NAME VARCHAR2(50));             


CREATE TABLE PRODUCTS
       (ID NUMBER CONSTRAINT PK_PRO_ID PRIMARY KEY, 
        NAME VARCHAR2(50),
        PRICE NUMBER(8,2),
        QUANTITY NUMBER(5),
        CAT_ID NUMBER CONSTRAINT FK_CAT_ID REFERENCES CATEGORIES);     
        
        
CREATE TABLE TRANSACTIONS
       (ID NUMBER CONSTRAINT PK_TRAN_ID PRIMARY KEY, 
        TRANSACTION_ID VARCHAR2(50),
        AMOUNT NUMBER(20,2),
        PAYMENT_BY VARCHAR2(50));     
        
     
CREATE TABLE PURCHASES
       (ID NUMBER CONSTRAINT PK_PUR_ID PRIMARY KEY, 
        INFO_ID NUMBER CONSTRAINT FK_INFO_ID_PUR REFERENCES INFORMATIONS,
        INVOICE VARCHAR2(50),
        TDATE DATE,
        EXP_DATE DATE,
        CAT_ID NUMBER CONSTRAINT FK_CAT_ID_PUR REFERENCES CATEGORIES,
        PRO_ID NUMBER CONSTRAINT FK_PRO_ID_PUR REFERENCES PRODUCTS,
        QUANTITY NUMBER(10),
        PRE_UNIT_PRICE NUMBER(10,2),
        NEW_UNIT_PRICE NUMBER(10,2),
        TRAN_ID NUMBER CONSTRAINT FK_TRAN_ID_PUR REFERENCES TRANSACTIONS,
        REMARKS VARCHAR2(50));   
        
CREATE TABLE SALES
       (ID NUMBER CONSTRAINT PK_SAL_ID PRIMARY KEY, 
        INFO_ID NUMBER CONSTRAINT FK_INFO_ID_SAL REFERENCES INFORMATIONS,
        INVOICE VARCHAR2(50),
        TDATE DATE,
        EXP_DATE DATE,
        CAT_ID NUMBER CONSTRAINT FK_CAT_ID_SAL REFERENCES CATEGORIES,
        PRO_ID NUMBER CONSTRAINT FK_PRO_ID_SAL REFERENCES PRODUCTS,
        QUANTITY NUMBER(10),
        PRE_UNIT_PRICE NUMBER(10,2),
        NEW_UNIT_PRICE NUMBER(10,2),
        TRAN_ID NUMBER CONSTRAINT FK_TRAN_ID_SAL REFERENCES TRANSACTIONS,
        REMARKS VARCHAR2(50));   
              
        